//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.12 at 02:21:16 PM EDT 
//


package gov.raleigh.employeeservice.service.impl;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FAType"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;element ref="{}Step1"/>
 *         &lt;element ref="{}Step2"/>
 *         &lt;element ref="{}Step3"/>
 *         &lt;element ref="{}ServiceAddress"/>
 *         &lt;element ref="{}CustomerName"/>
 *         &lt;element ref="{}MeterLocation"/>
 *         &lt;element ref="{}MeterSize"/>
 *         &lt;element ref="{}MeterModel"/>
 *         &lt;element ref="{}FieldActivityId"/>
 *         &lt;element ref="{}Status"/>
 *         &lt;element ref="{}DispatchGroup"/>
 *         &lt;element ref="{}ServicePointId"/>
 *         &lt;element ref="{}ServicePointType"/>
 *         &lt;element ref="{}ScheduledDate"/>
 *         &lt;element ref="{}Instructions"/>
 *         &lt;element ref="{}Cycle"/>
 *         &lt;element ref="{}Route"/>
 *         &lt;element ref="{}Sequence"/>
 *         &lt;element ref="{}CustomerPhoneNumber"/>
 *         &lt;element ref="{}ZipCode"/>
 *         &lt;element ref="{}ServicePointSourceStatus"/>
 *         &lt;element ref="{}ServicePointCreationDate"/>
 *         &lt;element ref="{}MeterInstallDate"/>
 *         &lt;element ref="{}PremiseType"/>
 *         &lt;element ref="{}Township"/>
 *         &lt;element ref="{}CityLimit"/>
 *         &lt;element ref="{}UseClass"/>
 *         &lt;element ref="{}XCoordinate"/>
 *         &lt;element ref="{}YCoordinate"/>
 *         &lt;element ref="{}FAClass"/>
 *         &lt;element ref="{}Priority"/>
 *         &lt;element ref="{}MeterBadgeNumber"/>
 *         &lt;element ref="{}Registers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "faType",
    "description",
    "step1",
    "step2",
    "step3",
    "serviceAddress",
    "customerName",
    "meterLocation",
    "meterSize",
    "meterModel",
    "fieldActivityId",
    "status",
    "dispatchGroup",
    "servicePointId",
    "servicePointType",
    "scheduledDate",
    "instructions",
    "cycle",
    "route",
    "sequence",
    "customerPhoneNumber",
    "zipCode",
    "servicePointSourceStatus",
    "servicePointCreationDate",
    "meterInstallDate",
    "premiseType",
    "township",
    "cityLimit",
    "useClass",
    "xCoordinate",
    "yCoordinate",
    "faClass",
    "priority",
    "meterBadgeNumber",
    "registers"
})
@XmlRootElement(name = "RequestMessage")
public class RequestMessage {

    @XmlElement(name = "FAType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String faType;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Step1", required = true)
    protected String step1;
    @XmlElement(name = "Step2", required = true)
    protected String step2;
    @XmlElement(name = "Step3", required = true)
    protected String step3;
    @XmlElement(name = "ServiceAddress", required = true)
    protected String serviceAddress;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "MeterLocation", required = true)
    protected String meterLocation;
    @XmlElement(name = "MeterSize", required = true)
    protected String meterSize;
    @XmlElement(name = "MeterModel", required = true)
    protected String meterModel;
    @XmlElement(name = "FieldActivityId", required = true)
    protected BigInteger fieldActivityId;
    @XmlElement(name = "Status", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(name = "DispatchGroup", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dispatchGroup;
    @XmlElement(name = "ServicePointId", required = true)
    protected BigInteger servicePointId;
    @XmlElement(name = "ServicePointType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String servicePointType;
    @XmlElement(name = "ScheduledDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String scheduledDate;
    @XmlElement(name = "Instructions", required = true)
    protected String instructions;
    @XmlElement(name = "Cycle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cycle;
    @XmlElement(name = "Route", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String route;
    @XmlElement(name = "Sequence", required = true)
    protected BigInteger sequence;
    @XmlElement(name = "CustomerPhoneNumber", required = true)
    protected String customerPhoneNumber;
    @XmlElement(name = "ZipCode", required = true)
    protected BigInteger zipCode;
    @XmlElement(name = "ServicePointSourceStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String servicePointSourceStatus;
    @XmlElement(name = "ServicePointCreationDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String servicePointCreationDate;
    @XmlElement(name = "MeterInstallDate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String meterInstallDate;
    @XmlElement(name = "PremiseType", required = true)
    protected String premiseType;
    @XmlElement(name = "Township", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String township;
    @XmlElement(name = "CityLimit", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cityLimit;
    @XmlElement(name = "UseClass", required = true)
    protected String useClass;
    @XmlElement(name = "XCoordinate", required = true)
    protected BigDecimal xCoordinate;
    @XmlElement(name = "YCoordinate", required = true)
    protected BigDecimal yCoordinate;
    @XmlElement(name = "FAClass", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String faClass;
    @XmlElement(name = "Priority", required = true)
    protected String priority;
    @XmlElement(name = "MeterBadgeNumber", required = true)
    protected BigInteger meterBadgeNumber;
    @XmlElement(name = "Registers", required = true)
    protected Registers registers;

    /**
     * Gets the value of the faType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAType() {
        return faType;
    }

    /**
     * Sets the value of the faType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAType(String value) {
        this.faType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the step1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep1() {
        return step1;
    }

    /**
     * Sets the value of the step1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep1(String value) {
        this.step1 = value;
    }

    /**
     * Gets the value of the step2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep2() {
        return step2;
    }

    /**
     * Sets the value of the step2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep2(String value) {
        this.step2 = value;
    }

    /**
     * Gets the value of the step3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStep3() {
        return step3;
    }

    /**
     * Sets the value of the step3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStep3(String value) {
        this.step3 = value;
    }

    /**
     * Gets the value of the serviceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAddress() {
        return serviceAddress;
    }

    /**
     * Sets the value of the serviceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAddress(String value) {
        this.serviceAddress = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the meterLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterLocation() {
        return meterLocation;
    }

    /**
     * Sets the value of the meterLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterLocation(String value) {
        this.meterLocation = value;
    }

    /**
     * Gets the value of the meterSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterSize() {
        return meterSize;
    }

    /**
     * Sets the value of the meterSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterSize(String value) {
        this.meterSize = value;
    }

    /**
     * Gets the value of the meterModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterModel() {
        return meterModel;
    }

    /**
     * Sets the value of the meterModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterModel(String value) {
        this.meterModel = value;
    }

    /**
     * Gets the value of the fieldActivityId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFieldActivityId() {
        return fieldActivityId;
    }

    /**
     * Sets the value of the fieldActivityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFieldActivityId(BigInteger value) {
        this.fieldActivityId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the dispatchGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatchGroup() {
        return dispatchGroup;
    }

    /**
     * Sets the value of the dispatchGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatchGroup(String value) {
        this.dispatchGroup = value;
    }

    /**
     * Gets the value of the servicePointId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServicePointId() {
        return servicePointId;
    }

    /**
     * Sets the value of the servicePointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServicePointId(BigInteger value) {
        this.servicePointId = value;
    }

    /**
     * Gets the value of the servicePointType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePointType() {
        return servicePointType;
    }

    /**
     * Sets the value of the servicePointType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePointType(String value) {
        this.servicePointType = value;
    }

    /**
     * Gets the value of the scheduledDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduledDate() {
        return scheduledDate;
    }

    /**
     * Sets the value of the scheduledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduledDate(String value) {
        this.scheduledDate = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructions(String value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the cycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCycle(String value) {
        this.cycle = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoute(String value) {
        this.route = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the customerPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPhoneNumber() {
        return customerPhoneNumber;
    }

    /**
     * Sets the value of the customerPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPhoneNumber(String value) {
        this.customerPhoneNumber = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZipCode(BigInteger value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the servicePointSourceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePointSourceStatus() {
        return servicePointSourceStatus;
    }

    /**
     * Sets the value of the servicePointSourceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePointSourceStatus(String value) {
        this.servicePointSourceStatus = value;
    }

    /**
     * Gets the value of the servicePointCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicePointCreationDate() {
        return servicePointCreationDate;
    }

    /**
     * Sets the value of the servicePointCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicePointCreationDate(String value) {
        this.servicePointCreationDate = value;
    }

    /**
     * Gets the value of the meterInstallDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeterInstallDate() {
        return meterInstallDate;
    }

    /**
     * Sets the value of the meterInstallDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeterInstallDate(String value) {
        this.meterInstallDate = value;
    }

    /**
     * Gets the value of the premiseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremiseType() {
        return premiseType;
    }

    /**
     * Sets the value of the premiseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremiseType(String value) {
        this.premiseType = value;
    }

    /**
     * Gets the value of the township property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTownship() {
        return township;
    }

    /**
     * Sets the value of the township property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTownship(String value) {
        this.township = value;
    }

    /**
     * Gets the value of the cityLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityLimit() {
        return cityLimit;
    }

    /**
     * Sets the value of the cityLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityLimit(String value) {
        this.cityLimit = value;
    }

    /**
     * Gets the value of the useClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseClass() {
        return useClass;
    }

    /**
     * Sets the value of the useClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseClass(String value) {
        this.useClass = value;
    }

    /**
     * Gets the value of the xCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getXCoordinate() {
        return xCoordinate;
    }

    /**
     * Sets the value of the xCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setXCoordinate(BigDecimal value) {
        this.xCoordinate = value;
    }

    /**
     * Gets the value of the yCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYCoordinate() {
        return yCoordinate;
    }

    /**
     * Sets the value of the yCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYCoordinate(BigDecimal value) {
        this.yCoordinate = value;
    }

    /**
     * Gets the value of the faClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFAClass() {
        return faClass;
    }

    /**
     * Sets the value of the faClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFAClass(String value) {
        this.faClass = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the meterBadgeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMeterBadgeNumber() {
        return meterBadgeNumber;
    }

    /**
     * Sets the value of the meterBadgeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMeterBadgeNumber(BigInteger value) {
        this.meterBadgeNumber = value;
    }

    /**
     * Gets the value of the registers property.
     * 
     * @return
     *     possible object is
     *     {@link Registers }
     *     
     */
    public Registers getRegisters() {
        return registers;
    }

    /**
     * Sets the value of the registers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Registers }
     *     
     */
    public void setRegisters(Registers value) {
        this.registers = value;
    }

}
